version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_blog
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  app:
    build: .
    environment:
      BLOG_DB_DRIVER: postgres
      BLOG_DB_DSN: postgres://postgres:postgres@db:5432/go_blog?sslmode=disable
      BLOG_JWT_SECRET: change_me
      BLOG_REDIS_ADDR: redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis